package com.example.blu_compose.model

import com.example.blu_compose.R

object CampusDataSource {
    val campusData = listOf(
        Campus(1, R.drawable.unpad,"Universitas Padjajaran","Universitas Padjadjaran atau bisa disingkat Unpad merupakan universitas negeri berlokasi di daerah Jatinangor, Sumedang, Jawa Barat. Meskipun terletak di Sumedang, Unpad sering dikenal sebagai salah satu universitas di Bandung. Bukan tanpa alasan, kampus Unpad dulunya memang terletak di Bandung, tepatnya di Jalan Dipatiukur yang kini menjadi kampus untuk pascasarjana", "Rp. 2.000.000 – 15.000.000"),
        Campus(2, R.drawable.itb,"Institut Teknologi Bandung","Institut Teknologi Bandung (ITB) berdiri sejak 3 Juli 1920 oleh kolonial Belanda dengan nama de Technische Hoogeschool te Bandung (TH). Setelah beberapa kali berganti nama, nama ITB diresmikan pada 2 Maret 1959. Sejak awal berdirinya, ITB merupakan perguruan tinggi negeri yang fokus pada disiplin ilmu teknik, ilmu pasti, dan ilmu alam.","Rp. 1.000.000 – 25.000.000"),
        Campus(3, R.drawable.upi,"Universitas Pendidikan Indonesia", "Universitas Pendidikan Indonesia (UPI) memiliki cikal bakal dari Perguruan Tinggi Pendidikan Guru (PTPG) yang merupakan bagian dari Unpad. Kemudian pada tahun 1963 memisahkan diri menjadi IKIP (Institut Keguruan dan Ilmu Pendidikan) Bandung. Pada tahun 1999, IKIP resmi berganti nama menjadi UPI.","Rp. 3.000.000 – 7.000.000"),
        Campus(4, R.drawable.isbi,"Institut Seni dan Budaya Indonesia","Cikal bakal dari Institut Seni dan Budaya Indonesia (ISBI) adalah Konservatori Tari (KORI) yang berkembang menjadi Akademi Seni Tari Indonesia (ASTI) Bandung pada tahun 1971. Kemudian ASTI berganti nama menjadi Sekolah Tinggi Seni Indonesia (STSI) pada tahun 1995 sampai akhirnya menjadi ISBI pada tahun 2014.","Rp. 500.000 – 2.500.000"),
        Campus(5, R.drawable.telu,"Telkom University","Universitas Telkom merupakan gabungan dari empat perguruan tinggi, yaitu Institut Teknologi Telkom (2007), Institut Manajemen Telkom (2008), Sekolah Tinggi Senirupa dan Desain Indonesia Telkom (2010), dan Politeknik Telkom (2007). Keempat perguruan tinggi tersebut resmi bergabung menjadi Universitas Telkom pada 14 Agustus 2013.","Rp. 6.000.000 – 20.000.000"),
        Campus(6, R.drawable.uinsgj,"UIN Sunan Gunung Djati Bandung","Universitas Islam Negeri (UIN) Sunan Gunung Djati Bandung berasal dari Institut Agama Islam Negeri (IAIN) Sunan Gunung Djati Bandung. IAIN tersebut berdiri sejak 8 April 1968 dan berubah menjadi UIN pada 10 Oktober 2005.","Rp. 400.000 – 4.000.000"),
        Campus(7, R.drawable.unikom, "Universitas Komputer", "Universitas Komputer atau biasa disingkat Unikom berdiri pada 8 Agustus 2000. Cikal bakal Unikom adalah dari Lembaga Pendidikan Komputer Indonesia Jerman (LPKIG) pada tahun 1994.","Rp. 5.000.000 – 8.000.000"),
        Campus(8, R.drawable.unpar,"Universitas Parahyangan","Universitas Katolik Parahyangan atau biasa disingkat Unpar merupakan salah satu perguruan swasta tertua yang ada di Bandung dan Indonesia. Awalnya Unpar merupakan Akademi Perniagaan yang didirikan oleh dua orang uskup pada 17 Januari 1955. Kemudian pada tahun 1961 resmi berganti nama menjadi Unpar.","Rp. 12.000.000 – 50.000.000"),
        Campus(9, R.drawable.unpas,"Universitas Pasundan","Universitas Pasundan atau bisa disingkat Unpas merupakan salah satu perguruan tinggi swasta tertua juga di Bandung. Unpas berdiri sejak 14 November 1960 oleh Paguyuban Pasundan.","Rp. 4.000.000 – 10.000.000"),
        Campus(10, R.drawable.uinb,"Universitas Islam Bandung","Universitas Islam Bandung atau bisa disingkat Unisba merupakan perguruan tinggi swasta di Bandung yang berdidi sejak tahun 1958 dengan nama Perguruan Islam Tinggi (PIT). Kemudian pada tahun 2007 resmi berganti menjadi Unisba.","Rp. 1.000.000 – 40.000.000")
    )
}